// Copyright 2025 The IREE Authors
//
// Licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

#ifndef IREE_COMPILER_DIALECT_LOOM_IR_LOOM_OPS_TD
#define IREE_COMPILER_DIALECT_LOOM_IR_LOOM_OPS_TD

include "iree/compiler/Dialect/Loom/IR/Tensor/TensorOps.td"
include "iree/compiler/Dialect/Loom/IR/Tile/TileOps.td"
include "iree/compiler/Dialect/Loom/IR/Test/TestOps.td"

#endif // IREE_COMPILER_DIALECT_LOOM_IR_LOOM_OPS_TD
