# Copyright 2025 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

load(
    "//build_tools/bazel:build_defs.oss.bzl",
    "iree_compiler_cc_library",
    "iree_gentbl_cc_library",
    "iree_td_library",
)

package(
    default_visibility = ["//visibility:public"],
    features = ["layering_check"],
    licenses = ["notice"],  # Apache 2.0
)

#===------------------------------------------------------------------------===#
# TableGen libraries
#===------------------------------------------------------------------------===#

iree_td_library(
    name = "td_files",
    srcs = [
        "DimOp.td",
        "SliceOp.td",
        "TensorOps.td",
        "UpdateOp.td",
    ],
    deps = [
        "//compiler/src/iree/compiler/Dialect/Loom/IR:td_files",
    ],
)

#===------------------------------------------------------------------------===#
# Code generation
#===------------------------------------------------------------------------===#

iree_gentbl_cc_library(
    name = "TensorOpsGen",
    tbl_outs = [
        (
            ["--gen-op-decls"],
            "TensorOps.h.inc",
        ),
        (
            ["--gen-op-defs"],
            "TensorOps.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "TensorOps.td",
    deps = [":td_files"],
)

iree_gentbl_cc_library(
    name = "TensorOpErrorsGen",
    tbl_outs = [
        (
            ["--gen-iree-op-error-tag-dispatch"],
            "TensorOpErrors.cpp.inc",
        ),
    ],
    tblgen = "//tools:iree-tblgen",
    td_file = "TensorOps.td",
    deps = [":td_files"],
)

#===------------------------------------------------------------------------===#
# C++ library
#===------------------------------------------------------------------------===#

iree_compiler_cc_library(
    name = "Tensor",
    srcs = [
        "DimOp.cpp",
        "SliceOp.cpp",
        "TensorOps.cpp",
        "UpdateOp.cpp",
    ],
    hdrs = [
        "TensorOps.h",
    ],
    textual_hdrs = [
        "TensorOpErrors.cpp.inc",
        "TensorOps.cpp.inc",
        "TensorOps.h.inc",
    ],
    deps = [
        ":TensorOpErrorsGen",
        ":TensorOpsGen",
        "//compiler/src/iree/compiler/Dialect/Loom/IR",
        "//compiler/src/iree/compiler/Dialect/Util/IR",
        "//compiler/src/iree/compiler/Utils",
        "@llvm-project//llvm:Support",
        "@llvm-project//mlir:ArithDialect",
        "@llvm-project//mlir:IR",
        "@llvm-project//mlir:InferTypeOpInterface",
        "@llvm-project//mlir:SideEffectInterfaces",
        "@llvm-project//mlir:Support",
    ],
)
