// Copyright 2025 The IREE Authors
//
// Licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

#ifndef IREE_COMPILER_UTILS_DIAGNOSTICS_H_
#define IREE_COMPILER_UTILS_DIAGNOSTICS_H_

#include <type_traits>
#include <utility>
#include "mlir/IR/Diagnostics.h"
#include "mlir/IR/Location.h"
#include "mlir/IR/Operation.h"

namespace mlir::iree_compiler {

//===----------------------------------------------------------------------===//
// Ergonomic Error Emission API
//===----------------------------------------------------------------------===//
//
// This file provides a streamlined API for emitting structured errors defined
// in IREE's TableGen-based error system. The API supports emplace-style
// construction of error arguments and integrates seamlessly with MLIR's
// diagnostic system.
//
// Usage:
//
//   // Errors with manual arguments - emplace-style construction:
//   return emitErrorCode<ERR_UTIL_VERIFY_0001>(
//       op, higherName, lowerName, higherRank, lowerRank, higherType, lowerType
//   );
//
//   // Op-specific errors with automatic field extraction:
//   return emitErrorCode<ERR_LOOM_ENCODING_0001>(tileBroadcastOp);
//
//   // Errors without arguments:
//   return emitErrorCode<ERR_UTIL_FOLD_0001>(op);
//
//   // Chaining with additional context:
//   return emitErrorCode<ERR_UTIL_VERIFY_0001>(op, ...) << "additional
//   context";
//
//   // Location-based overload:
//   return emitErrorCode<ERR_UTIL_TYPE_0001>(loc, operandName, actualType);
//
// The emitErrorCode function returns InFlightDiagnostic, allowing it to be used
// in return statements and chained with operator<< for additional context.
//
// Design:
// - Uses C++17 `if constexpr` for compile-time dispatch based on whether the
//   error type has an Args struct
// - Leverages perfect forwarding and aggregate initialization for zero-cost
//   argument construction
// - Type-safe: only accepts arguments matching the error's Args struct
// - Tag dispatching pattern enables op-specific overloads for automatic field
//   extraction (implemented via iree-tblgen generated detail::emitImpl)
//
//===----------------------------------------------------------------------===//

//===----------------------------------------------------------------------===//
// Error Tag Dispatching Infrastructure
//===----------------------------------------------------------------------===//
//
// ErrorTag<T> enables tag dispatching for type-safe op-specific error emission.
// This pattern solves the template specialization linkage problem by using
// function overloading instead of template specialization.
//
// How it works:
// 1. emitErrorCode<ErrID>(concreteOp) creates ErrorTag<ErrID>{} and dispatches
//    to detail::emitImpl(ErrorTag<ErrID>{}, concreteOp)
// 2. iree-tblgen generates overloads of detail::emitImpl for each (error, op)
//    pair declared in TableGen
// 3. C++ overload resolution selects the best match at compile time
// 4. Generated implementations auto-extract fields from the concrete op
//
// Benefits:
// - Standard function overloading (no template specialization)
// - Works across translation units (.cpp implementations)
// - Clear compile errors if (error, op) pair not supported
// - Zero runtime overhead (tag optimized away)
//
// Example generated code:
//   namespace detail {
//     InFlightDiagnostic emitImpl(ErrorTag<ERR_LOOM_ENCODING_0001>,
//                                 TileBroadcastOp op) {
//       return ERR_LOOM_ENCODING_0001::emit(op.getOperation(),
//         ERR_LOOM_ENCODING_0001::Args{
//           .operandNames = {"operand", "result"},
//           .encodings = {
//             cast<TileType>(op.getOperand().getType()).getEncoding(),
//             cast<TileType>(op.getResult().getType()).getEncoding()
//           }
//         });
//     }
//   }
//
//===----------------------------------------------------------------------===//

// Empty tag type for error ID dispatching.
// Used to drive function overload resolution for op-specific error emission.
template <typename ErrorType>
struct ErrorTag {};

// Detail namespace for generated op-specific error emission implementations.
// iree-tblgen generates overloads of emitImpl for each (error, op) pair.
namespace detail {

// Fallback template that generates a compile error for unsupported
// combinations. This is needed so that qualified lookup (detail::emitImpl)
// finds something during template definition parsing. The actual overloads are
// generated by iree-tblgen and should be included before calling
// emitErrorCode<E>(op).
//
// Generated overloads will appear via #include of generated files.
// Example:
//   InFlightDiagnostic emitImpl(ErrorTag<ERR_FOO>, ConcreteOp op);
template <typename ErrorTag, typename OpTy>
InFlightDiagnostic emitImpl(ErrorTag, OpTy) {
  static_assert(sizeof(OpTy) == 0,
                "No emitImpl overload generated for this (error, op) pair. "
                "Ensure the TileOpErrors.cpp.inc is included.");
  return InFlightDiagnostic(); // Never reached.
}

} // namespace detail

// Type trait to detect if ErrorType has an Args member type.
template <typename, typename = void>
struct has_args_type : std::false_type {};

template <typename T>
struct has_args_type<T, std::void_t<typename T::Args>> : std::true_type {};

//===----------------------------------------------------------------------===//
// Operation-based error emission
//===----------------------------------------------------------------------===//

// Emit a structured error from the given operation.
//
// This function supports both errors with arguments (using emplace-style
// construction) and errors without arguments. The appropriate overload is
// selected at compile-time using `if constexpr`.
//
// For errors with arguments, the Args struct is constructed in-place using
// aggregate initialization from the provided argument pack.
//
// Returns InFlightDiagnostic for chaining and return statement compatibility.
template <typename ErrorType, typename... Args>
InFlightDiagnostic emitErrorCode(Operation *op, Args &&...args) {
  if constexpr (has_args_type<ErrorType>::value) {
    // Error has Args struct - construct in-place using aggregate
    // initialization.
    typename ErrorType::Args errorArgs{std::forward<Args>(args)...};
    return ErrorType::emit(op, errorArgs);
  } else {
    // Error has no Args struct - forward arguments directly to emit().
    return ErrorType::emit(op, std::forward<Args>(args)...);
  }
}

//===----------------------------------------------------------------------===//
// Location-based error emission
//===----------------------------------------------------------------------===//

// Emit a structured error from the given location.
//
// This overload allows emitting errors from a Location instead of an
// Operation, useful for type checking, attribute parsing, and other contexts
// where no operation is available.
//
// Returns InFlightDiagnostic for chaining and return statement compatibility.
template <typename ErrorType, typename... Args>
InFlightDiagnostic emitErrorCode(Location loc, Args &&...args) {
  if constexpr (has_args_type<ErrorType>::value) {
    // Error has Args struct - construct in-place using aggregate
    // initialization.
    typename ErrorType::Args errorArgs{std::forward<Args>(args)...};
    return ErrorType::emit(loc, errorArgs);
  } else {
    // Error has no Args struct - forward arguments directly to emit().
    return ErrorType::emit(loc, std::forward<Args>(args)...);
  }
}

//===----------------------------------------------------------------------===//
// Direct Args overload (for advanced use cases)
//===----------------------------------------------------------------------===//

// Emit a structured error with pre-constructed Args.
//
// This overload is provided for cases where the Args struct needs to be
// constructed explicitly (e.g., when arguments are computed conditionally).
//
// Most code should use the emplace-style overload above for brevity.
template <typename ErrorType>
InFlightDiagnostic emitErrorCode(Operation *op,
                                 const typename ErrorType::Args &errorArgs) {
  return ErrorType::emit(op, errorArgs);
}

// Location-based overload for pre-constructed Args.
template <typename ErrorType>
InFlightDiagnostic emitErrorCode(Location loc,
                                 const typename ErrorType::Args &errorArgs) {
  return ErrorType::emit(loc, errorArgs);
}

//===----------------------------------------------------------------------===//
// Tag-Dispatched Op-Specific Error Emission
//===----------------------------------------------------------------------===//

// Emit an error with automatic field extraction from a concrete op.
//
// This overload uses tag dispatching to select op-specific error emission
// implementations generated by iree-tblgen. The generated detail::emitImpl
// functions automatically extract the required fields from the concrete op
// type and construct the error arguments.
//
// This overload is selected when passing a concrete op type (not Operation*)
// and an op-specific implementation exists. If no specific implementation
// exists, a compile error will indicate the missing (error, op) pair.
//
// Example:
//   return emitErrorCode<ERR_LOOM_ENCODING_0001>(tileBroadcastOp);
//   // Automatically extracts operand/result encodings from the op
//
// Returns InFlightDiagnostic for chaining and return statement compatibility.
template <typename ErrorType, typename OpTy>
InFlightDiagnostic emitErrorCode(OpTy op) {
  // Dispatch to generated detail::emitImpl overload using tag.
  // The ErrorTag<ErrorType> allows overload resolution to select the correct
  // implementation based on both the error type and op type.
  return detail::emitImpl(ErrorTag<ErrorType>{}, op);
}

} // namespace mlir::iree_compiler

#endif // IREE_COMPILER_UTILS_DIAGNOSTICS_H_
