# Copyright 2025 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

load("//build_tools/bazel:enforce_glob.bzl", "enforce_glob")
load("//build_tools/bazel:iree_lit_test.bzl", "iree_lit_test_suite")

package(
    features = ["layering_check"],
    licenses = ["notice"],  # Apache 2.0
)

iree_lit_test_suite(
    name = "lit",
    srcs = enforce_glob(
        [
            "alloca_op.mlir",
            "alloca_op_invalid.mlir",
            "broadcast_op.mlir",
            "broadcast_op_fold.mlir",
            "broadcast_op_invalid.mlir",
            "constant_op.mlir",
            "constant_op_invalid.mlir",
            "copy_op.mlir",
            "copy_op_fold.mlir",
            "copy_op_invalid.mlir",
            "dim_op.mlir",
            "dim_op_fold.mlir",
            "dim_op_invalid.mlir",
            "elementwise_op.mlir",
            "elementwise_op_fold.mlir",
            "elementwise_op_invalid.mlir",
            "fill_op.mlir",
            "fill_op_invalid.mlir",
            "poison_chain.mlir",
            "slice_op.mlir",
            "slice_op_fold.mlir",
            "slice_op_invalid.mlir",
            "tile_ops.mlir",
            "update_op.mlir",
            "update_op_fold.mlir",
            "update_op_invalid.mlir",
            "yield_op.mlir",
        ],
        include = ["*.mlir"],
    ),
    cfg = "//compiler:lit.cfg.py",
    tools = [
        "//tools:iree-opt",
        "@llvm-project//llvm:FileCheck",
    ],
)
